@startuml
!include Style.puml


participant ":CardCollector" as CardCollector
participant ":CommandContext" as CommandContext COMMANDCONTEXT_COLOR_PRIMARY
participant ":Parser" as Parser PARSER_COLOR_PRIMARY
participant ":HistoryCommand" as HistoryCommand COMMAND_COLOR_PRIMARY
participant ":Ui" as Ui UI_COLOR_PRIMARY

CardCollector -> Parser : parse("history all added")
activate Parser

create HistoryCommand
Parser -> HistoryCommand
activate HistoryCommand
HistoryCommand --> Parser : command
deactivate HistoryCommand

Parser --> CardCollector : command
deactivate Parser
CardCollector -[hidden]-> Parser

'We are done with the parser, lets create the command context and execute the command'
create CommandContext
CardCollector -> CommandContext
activate CommandContext
CommandContext --> CardCollector : context
deactivate

CardCollector -> HistoryCommand : execute(context)
activate HistoryCommand

HistoryCommand -> Ui: printHistory(...)
activate Ui
Ui --> HistoryCommand
deactivate Ui

HistoryCommand --> CardCollector : commandResult
deactivate HistoryCommand
CardCollector -[hidden]-> Parser
destroy HistoryCommand
@enduml


@enduml