@startuml
!include Style.puml

participant ":CardCollector" as CardCollector CARDCOLLECTOR_COLOR_PRIMARY
participant ":Parser" as Parser PARSER_COLOR_PRIMARY
participant ":HistoryCommand" as HistoryCommand COMMAND_COLOR_PRIMARY
participant ":Ui" as Ui UI_COLOR_PRIMARY

CardCollector -> Parser : parse("history added all")
activate Parser

create HistoryCommand
Parser -> HistoryCommand
activate HistoryCommand
HistoryCommand --> Parser : command
deactivate HistoryCommand

Parser --> CardCollector : command
deactivate Parser
CardCollector -[hidden]-> Parser

'We are done with the parser, lets execute the command'
CardCollector -> HistoryCommand : execute(...)
activate HistoryCommand

alt #fafafa CardHistoryType.ADDED
    HistoryCommand -> Ui: printAddedHistory(...)
    activate Ui
    Ui --> HistoryCommand
    deactivate Ui
else CardHistoryType.MODIFIED
    HistoryCommand -> Ui: printModifiedHistory(...)
    activate Ui
    Ui --> HistoryCommand
    deactivate Ui
else CardHistoryType.Removed
    HistoryCommand -> Ui: printRemovedHistory(...)
    activate Ui
    Ui --> HistoryCommand
    deactivate Ui
end

HistoryCommand --> CardCollector : commandResult
deactivate HistoryCommand
CardCollector -[hidden]-> Parser
destroy HistoryCommand
@enduml


@enduml