/'
 '@@HX2003-reused
 'Reused from https://github.com/se-edu/addressbook-level3/blob/master/docs/diagrams/style.puml
 'with some modifications
 '/

/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/

'Secondary colors derived from Color Palette feature of https://htmlcolorcodes.com/'
!define PARSER_COLOR_PRIMARY #4536FF
!define PARSER_COLOR_BACKGROUND #BCB8FF
!define COMMAND_COLOR_PRIMARY #BC00D1
!define COMMAND_COLOR_BACKGROUND #F8B8FF
!define COMMANDCONTEXT_COLOR_PRIMARY #D1006C
!define COMMANDCONTEXT_COLOR_BACKGROUND #FFE6F3
!define UI_COLOR_PRIMARY #D16C00
!define UI_COLOR_BACKGROUND ##FFDCB8
!define CARDSLIST_COLOR_PRIMARY #009BA3
!define CARDSLIST_COLOR_BACKGROUND #B8FBFF

skinparam Package {
    BackgroundColor #FFFFFF
    BorderThickness 1
    FontSize 16
}

skinparam Class {
    FontSize 16
    FontColor #?black:white
    BorderThickness 1
    FontName Arial
}

skinparam Actor {
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #?black:white
    FontName Arial
}

skinparam Participant {
    FontColor #?black:white
    Padding 20
}

skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle
skinparam classAttributeIconSize 0

hide footbox
hide circle